@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.testCrafter.lootItemConditions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;