@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.testCrafter.copperBlockLike;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;