@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.testCrafter;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;