@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.testCrafter.blocks.customCrafter.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;