@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.testCrafter.blocks.customCrafter;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;